language: java
jdk: openjdk8
services: mysql
before_install:
  - sudo mysql -e "CREATE DATABASE library;"
  - echo "UPDATE mysql.user SET password=PASSWORD('mysql') WHERE user='root';\nFLUSH PRIVILEGES;" | mysql -u root
