version: "3"
services:
  # mariadb:
  #   image: mariadb
  #   container_name: mariadb
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mysql
  #   healthcheck:
  #     test: mysql --user=root --password=mysql -h 172.16.238.4
  #     interval: 5s
  #     retries: 20
  #   networks:
  #     library_net:
  #       ipv4_address: 172.16.238.2
  #   volumes:
  #         - mysql-volume:/var/lib/mysql
  library-ms:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - database_ip=172.16.238.2
    container_name: library-ms
    ports:
      - 8080:8080
    networks:
      net:
        ipv4_address: 172.16.238.3
    deploy:
      replicas: 2
      # restart_policy:
      #   condition: on-failure
  library-web-app:
    image: library-app:latest
    container_name: library-web-app
    ports:
      - 8000:80
    networks:
      net:
        ipv4_address: 172.16.238.4
    deploy:
      replicas: 2
      # restart_policy:
      #   condition: on-failure
  library-admin-panel:
    image: library-admin-panel:latest
    container_name: library-admin-panel
    ports:
      - 8001:80
    networks:
      net:
        ipv4_address: 172.16.238.5
    deploy:
      replicas: 2
      # restart_policy:
      #   condition: on-failure

# volumes:
#   mysql-volume:

networks:
  net:

