version: "3.7"
services:

   mysql:
     image: mysql:5.6
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: mysql
       MYSQL_DATABASE: library
     networks:
       default:
         ipv4_address: 172.16.238.2
     volumes:
           - mysql-volume:/var/lib/mysql

   library-ms:
       build:
         context: .
         dockerfile: Dockerfile
       depends_on:
         - mysql
       image: docker.io/anh3h/library-server:latest
       environment:
         SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library?autoReconnect=true&useSSL=false
         GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcloud
       secrets:
         - gcloud
       ports:
         - 8080:8080
       networks:
         default:
           ipv4_address: 172.16.238.3
#       healthcheck:
#         test: curl -f -s http://localhost:8080 || exit 1
#         interval: 1m30s
#         timeout: 30s
#         retries: 3
       deploy:
         replicas: 1
         restart_policy:
           condition: on-failure

secrets:
  gcloud:
    file: ./key.json

volumes:
   mysql-volume:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.238.0/24"

