security:
  oauth2:
    client:
      client-id: admin
      client-secret: password
      refresh-token-validity-seconds: 10000
      access-token-validity-seconds: 3600
    resource:
      id: oauth2_id


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?autoReconnect=true&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
#        boot:
#          autoconfigure: DEBUG
