apiVersion: v1
kind: Service
metadata:
  name: library-app-service
  namespace: default
spec:
  selector:
    app: library-app
  ports:
    - port: 8000
      targetPort: 80
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: library-app-cluster
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
      - name: library-app
        image: docker.io/anh3h/library-app:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
